### ISSUE TITLE
Palindrome checker using react

### ISSUE THREAD

**Issue by amrutha-m206** [SahilKumarIN/React-Minor-Projects#16]
This will include a form input where users can enter text, and when they click the "Check" button, it will display whether the text is a palindrome.

can i get it assigned under hacktoberfest and hacktoberfest-accepted

**Comment by SahilKumarIN** [comment]
Yes, go for it.

**Comment by amrutha-m206** [comment]
can i get it assigned with hacktoberfest-accepted  labels
